# Time tacker API

@baseUrl = http://localhost:8000/api/v1/tasks


### POST the TaskList
POST {{baseUrl}}

### GET the TaskList
GET {{baseUrl}}

### UPDATE the TaskList
PUT {{baseUrl}}

### DELETE the TaskList
DELETE {{baseUrl}}