# Time tacker API

@baseUrl = http://localhost:8000/api/v1/tasks


### POST the TaskList
POST {{baseUrl}}
Content-Type: application/json

{
    "task" : "drive",
    "hr": "hahah"
   
    

}


### GET the TaskList
GET {{baseUrl}}

### UPDATE the TaskList
PATCH {{baseUrl}}
Content-Type: application/json

{
    "_id":"6a16a98a742d9a2ba3d67ecd",
    "hr": 20,
    "type":"bad"
}

### DELETE the TaskList
DELETE {{baseUrl}}/6a16a98a742d9a2ba3d67ecd